FROM tiangolo/uvicorn-gunicorn:python3.10

LABEL maintainer="Fat Plants MU <fatplantsmu@gmail.com>"

WORKDIR /app

COPY requirements.txt /app/requirements.txt
# RUN apt install libgl1-mesa-glx
RUN apt-get update && apt-get install -y python3-opencv
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Install BLAST packages
RUN apt-get update && apt-get install -y ncbi-blast+
ENV PATH="/usr/bin/blast:${PATH}"

# Set environment variables
ENV place=docker
ENV APP_ENV=dev

COPY . /app

EXPOSE 5004

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5004"]